// Code generated by hertz generator.

package main

import (
	"CarBuyerAssitance/biz/dal"
	"CarBuyerAssitance/biz/mw/jwt"
	"CarBuyerAssitance/biz/router"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/config"
	"CarBuyerAssitance/pkg/utils"
	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	config.Init("main")
	dal.Init()
	jwt.Init()
	service.Init()
}
func main() {
	listenAddr, err := utils.GetAvailablePort()
	if err != nil {
		logger.Fatalf("get available port failed, err: %v", err)
	}
	h := server.New(
		server.WithHostPorts(listenAddr),
		server.WithHandleMethodNotAllowed(true),
	)
	router.GeneratedRegister(h)
	h.Spin()
}
