// Code generated by hertz generator.

package consult

import (
	"CarBuyerAssitance/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consult0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryconsultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserscoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _giftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querygiftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buygiftMw() []app.HandlerFunc {
	// your code...
	return nil
}
