// Code generated by hertz generator.

package consult

import (
	consult "CarBuyerAssitance/biz/model/consult"
	"CarBuyerAssitance/biz/pack"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/biz/service/model"
	"CarBuyerAssitance/pkg/errno"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

// Consult .
// @router /api/consult/purchase [GET]
func Consult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.ConsultRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(consult.ConsultResponse)
	cd, id, err := service.NewConsultService(ctx, c).Consult(&model.Consult{
		BudgetRange:     req.BudgetRange,
		PreferredType:   req.PreferredType,
		UseCase:         req.UseCasecase,
		FuelType:        req.FuelType,
		BrandPreference: req.BrandPreference,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ConsultResult(cd, id)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryConsult .
// @router /api/consult/query [GET]
func QueryConsult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.QueryConsultRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(consult.QueryConsultResponse)
	data, err := service.NewConsultService(ctx, c).QueryConsult(int(req.ConsultID))
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Consultation(data)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryUserScore .
// @router /api/score/user/query [GET]
func QueryUserScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.QueryUserScoreRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(consult.QueryUserScoreResponse)
	data, err := service.NewConsultService(ctx, c).QueryUserPoint()
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.PointList(data)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryGift .
// @router /api/score/gift/query [GET]
func QueryGift(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.QueryGiftRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(consult.QueryGiftResponse)

	gift, err := service.NewConsultService(ctx, c).QueryGift()
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Gift(gift)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// BuyGift .
// @router /api/score/gift/purchase [POST]
func BuyGift(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.BuyGiftRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(consult.BuyGiftResponse)
	info, err := service.NewConsultService(ctx, c).BuyGift(req.GiftID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Order(info)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryOrder .
// @router /api/score/order/query [GET]
func QueryOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.QueryOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(consult.QueryOrderResponse)
	info, num, err := service.NewConsultService(ctx, c).QueryOrderByUId(req.UserID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.OrderList(info, num)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
